services:
  - type: web
    name: carhaki
    runtime: python
    plan: free
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python manage.py create_admin
    startCommand: "gunicorn carhaki.wsgi:application --workers 2 --timeout 60 --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: carhaki.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
