# Generated by Django 5.0.7 on 2026-05-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("NHTSA", "NHTSA (Free)"),
                            ("VINAUDIT", "VinAudit"),
                            ("OTOFACTS", "OtoFacts"),
                            ("CARCHECK_JP", "CarCheck.jp"),
                            ("ANTHROPIC", "Anthropic Claude"),
                            ("FLUTTERWAVE", "Flutterwave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("endpoint", models.CharField(max_length=200)),
                ("identifier", models.CharField(blank=True, max_length=30)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("success", models.BooleanField(default=True)),
                ("response_time_ms", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "API Log",
                "verbose_name_plural": "API Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usd_to_ugx_rate",
                    models.DecimalField(decimal_places=2, default=3720, max_digits=10),
                ),
                (
                    "basic_report_ugx",
                    models.DecimalField(decimal_places=2, default=35000, max_digits=12),
                ),
                (
                    "full_report_ugx",
                    models.DecimalField(decimal_places=2, default=75000, max_digits=12),
                ),
                (
                    "dealer_pack_10_ugx",
                    models.DecimalField(
                        decimal_places=2, default=600000, max_digits=12
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Configuration",
            },
        ),
    ]
