# Generated by Django 5.0.7 on 2026-05-04 23:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecallAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vin", models.CharField(max_length=17)),
                ("recall_number", models.CharField(max_length=50)),
                ("component", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("remedy", models.TextField(blank=True)),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("is_open", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("NHTSA", "NHTSA"), ("OTOFACTS", "OtoFacts")],
                        default="NHTSA",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recall Alert",
                "verbose_name_plural": "Recall Alerts",
                "unique_together": {("vin", "recall_number")},
            },
        ),
        migrations.CreateModel(
            name="VehicleSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identifier", models.CharField(max_length=25)),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("VIN", "VIN (USA)"),
                            ("CHASSIS", "Chassis Number (Japan)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "source_country",
                    models.CharField(
                        choices=[("USA", "USA"), ("JAPAN", "Japan")], max_length=5
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("basic_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Search",
                "verbose_name_plural": "Vehicle Searches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("BASIC", "Basic Report"), ("FULL", "Full Report")],
                        default="FULL",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("processed_data", models.JSONField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True)),
                (
                    "overall_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A — Excellent"),
                            ("B", "B — Good"),
                            ("C", "C — Acceptable"),
                            ("D", "D — Concerning"),
                            ("E", "E — Poor"),
                            ("F", "F — Critical Risk"),
                        ],
                        max_length=1,
                    ),
                ),
                ("risk_score", models.IntegerField(default=100)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="reports/pdfs/"),
                ),
                ("share_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="vehicles.vehiclesearch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Report",
                "verbose_name_plural": "Vehicle Reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
